### ISSUE TITLE
CloudApi set_output only allows turning off

### ISSUE THREAD

**Issue by kneirinck** [openmotics/sdk#2]
When using the python CloudApi.set_output call it only works when setting on to False.
When setting it to True nothing happens.

**Comment by khenderick** [comment]
Reproduced. It seems to be working fine when using the local client, but doesn't work on the cloud client.

**Comment by fryckbos** [comment]
This should be fixed now, there was a discrepancy between the local api and the cloud api. The local api uses the parameter 'is_on', while the cloud api uses the parameter 'on'. According to our documentation, the local api is correct. I changed the cloud api to use 'is_on'.

**Comment by khenderick** [comment]
Confirmed to be working as expected now.
